version: '3'

services:
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
        volumes:
            - ./data:/data/db
        networks:
            - app_network
    web:
        container_name: web
        build:
            context: .
            dockerfile: ./apps/web/Dockerfile
        restart: always
        ports:
            - 3000:3000
        networks:
            - app_network
        environment:
            - VITE_APP_API_URL=http://localhost:8000
    api:
        container_name: api
        build:
            context: .
            dockerfile: ./apps/api/Dockerfile
        restart: always
        ports:
            - 8000:8000
        networks:
            - app_network
        depends_on:
            - mongo
        environment:
            - MONGO_URL=mongodb://mongo:27017/quiz
            - PORT=8000
networks:
    app_network:
